### ISSUE TITLE
Proper Fully Responsive Home page with interactivity

### ISSUE THREAD

**Issue by r1shayanr7** [RohittCodes/codemonkey.js#1]
## Issue Description 

The home page is currently not responsive on all devices and dimensions and it does not have a proper structure. The other pages are under construction. The elements are not interactive enough.

## Solutions

Proper and interactive structure for the elements

Fully responsive layout on all devices and dimensions

## Screenshots

![Screenshot 2024-05-28 233909](https://github.com/RohittCodes/codemonkey.js/assets/167475552/df57b783-0e0a-4ac0-ab0b-21dc9fd26dc8)
![Screenshot 2024-05-28 233810](https://github.com/RohittCodes/codemonkey.js/assets/167475552/23ab10d6-f316-4ab0-a47b-22d41cc246c3)

## Program 

SSOC 24

**Comment by r1shayanr7** [comment]
@RohittCodes kindly assign this issue to me. i will fix it all

**Comment by rohittcodes** [comment]
Hey @r7projects-shayan, this repo was meant for a Quine.sh submission, you can contribute to it after the quest get's completed.

PS: It's not an SSOC 24 project.
